%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1
odom: 1

imu_topic: "/imu/data_raw"
image0_topic: "/stereo/left/image_mono"
image1_topic: "/stereo/right/image_mono"
output_path: "/home/myk/slam_lrn/output/kitti/m_gps_s/"
gt_path: "/home/wzb/datasets/KAIST/urban39/global_pose.csv"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 1280
image_height: 560
   
info_x: 20 # 20 # mono
info_y: 20 # 20 # mono
info_z: 20 # 20 # mono
info_qw: 0.00001
info_qy: 0.00001
info_qz: 20 # 9 # mono
info_vx: 20 # 20 # mono
info_vy: 20 # 20 # mono
info_vz: 20 # 20 # mono
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [
        -6.80499e-03, -1.53215e-02,  9.99850e-01,  1.71239e+00,
        -9.99977e-01,  3.34627e-04, -6.80066e-03,  2.47401e-01,
        -2.30383e-04, -9.99883e-01, -1.53234e-02, -1.15890e-01,
         0.00000e+00,  0.00000e+00,  0.00000e+00,  1.00000e+00 ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [
        -0.00326022, -0.01989934,  0.99978721,  1.70880565,
        -0.99999206,  0.00243209, -0.00321241, -0.22772958,
        -0.00236767, -0.99979947, -0.01990713, -0.11811928,
        0.        ,  0.        ,  0.        , 1.     ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 3000            # max feature number in feature tracking
min_dist: 20            # min distance between two features 
freq: 20                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.1   # max solver itration time (ms), to guarantee real time
max_num_iterations: 20   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 2.0000e-3          # accelerometer measurement noise standard deviation. 
gyr_n: 1.6968e-04         # gyroscope measurement noise standard deviation.     
acc_w: 3.0000e-3        # accelerometer bias random work noise standard deviation.  
gyr_w: 1.9393e-05       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.01                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/wzb/project/huawei/vo_gps/catkin_ws_vio_gps/src/VINS-Fusion/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
